name: scrape
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
    - name: scrape_and_commit
      run: |
        python3 dig.py -urls
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "- update releases registry"
        git pull --rebase
        git push origin HEAD:main
